Areas/Logging/Controllers/ManageLogController.cs
using DataRooms.UI.Areas.Logging.Models;
using DataRooms.UI.Code.Helpers;
using DataRooms.UI.Models;
using DataRooms.UI.WebApiHelpers;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DataRooms.UI.Areas.Logging.Controllers
{
    [SessionExpire]
    public class ManageLogController : Controller
    {
        private LoggerApiService _service { get; set; }
        private XMLLogService _xmlLogService { get; set; }
        int companyId = 0;
        public ManageLogController()
        {
            var token = Convert.ToString(System.Web.HttpContext.Current.Session["AuthToken"]);
            _service = new LoggerApiService(token);
            companyId = Convert.ToInt32(System.Web.HttpContext.Current.Session["CompanyId"]);
            var company = DataCache.Companies.Single(x => x.Id == companyId);
            _xmlLogService = new XMLLogService(company.LogsStoragePath);
        }


        [HttpGet]
        public ActionResult List()
        {
            try
            {
                var model = new ActivityLogModel();
                GetAllActivityLogsAsync(model);
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult List(ActivityLogModel model)
        {
            try
            {
                GetAllActivityLogsAsync(model);
                return View(model);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public void GetAllActivityLogsAsync(ActivityLogModel model)
        {
            try
            {
                model.SortColumn = string.IsNullOrEmpty(model.SortColumn) ? "CreatedOn" : model.SortColumn;
                IPagedList<ActivityLog> logs = null;
                switch (model.SortColumn)
                {
                    case "CreatedOn":
                        if (model.SortOrder.Equals("desc"))
                            logs = (_xmlLogService.GetActivityLogs()).OrderByDescending
                                    (m => m.CreatedOn).ToPagedList(model.CurrentPage, model.RecordsPerPage);
                        else
                            logs = (_xmlLogService.GetActivityLogs()).OrderBy
                                    (m => m.CreatedOn).ToPagedList(model.CurrentPage, model.RecordsPerPage);
                        break;
                    case "UserName":
                        if (model.SortOrder.Equals("desc"))
                            logs = (_xmlLogService.GetActivityLogs()).OrderByDescending
                                    (m => m.CreatorName).ToPagedList(model.CurrentPage, model.RecordsPerPage);
                        else
                            logs = (_xmlLogService.GetActivityLogs()).OrderBy
                                    (m => m.CreatorName).ToPagedList(model.CurrentPage, model.RecordsPerPage);
                        break;
                    case "ActivityCategory":
                        if (model.SortOrder.Equals("desc"))
                            logs = (_xmlLogService.GetActivityLogs()).OrderByDescending
                                    (m => m.ActivityCategory).ToPagedList(model.CurrentPage, model.RecordsPerPage);
                        else
                            logs = (_xmlLogService.GetActivityLogs()).OrderBy
                                    (m => m.ActivityCategory).ToPagedList(model.CurrentPage, model.RecordsPerPage);
                        break;
                    case "Default":
                        logs = (_xmlLogService.GetActivityLogs()).OrderByDescending
                            (m => m.CreatedOn).ToPagedList(model.CurrentPage, model.RecordsPerPage);
                        break;
                }

                model.PagedActivityLogs = logs;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public JsonResult GetDataLogsbyActivityLogId(int activitylogid)
        {
            try
            {
                IEnumerable<DataLog> logs = _xmlLogService.GetDataLogsbyActivityId(activitylogid);// await _service.GetDataLogs(activitylogid,"empty");
                ActivityLogModel model = new ActivityLogModel();
                if(logs!=null && logs.Count() > 0)
                {
                    model.DataLogs = new List<DataLogObject>();
                    foreach (var log in logs)
                    {
                        DataLogObject dataLogObject = new DataLogObject();
                        dataLogObject.TableName = log.TableName;
                        dataLogObject.OriginalData = GetObjectfromJson(log.TableName,log.OriginalData);
                        dataLogObject.ModifiedData = GetObjectfromJson(log.TableName,log.ModifiedData);
                        //dataLogObject.Changes = GetObjectfromJson(log.TableName,log.Changes);
                        model.DataLogs.Add(dataLogObject);
                    }
                }
                JsonResult jr = Json(new
                {
                    HTML = this.RenderPartialView(@"~\Areas\Logging\Views\Shared\_datalogs.cshtml", model)
                });
                jr.MaxJsonLength = int.MaxValue;
                jr.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
                return jr;
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        public Dictionary<string, string> GetObjectfromJson(string tablename,string jsonData)
        {
            Type t = Type.GetType("DataRooms.UI.Models." + tablename);
            var originalData = JsonConvert.DeserializeObject(jsonData, t);
            Dictionary<string, string> dictionary = new Dictionary<string, string>();
            var properties = t.GetProperties();
            if(properties!=null && properties.Count() > 0)
            {
                foreach(var property in properties)
                {
                    dictionary.Add(property.Name, GetPropValue(originalData, property.Name));
                }
            }
            return dictionary;
        }

        private static string FormatJson(string json)
        {
            dynamic parsedJson = JsonConvert.DeserializeObject(json);
            return JsonConvert.SerializeObject(parsedJson, Formatting.Indented);
        }

        public static string GetPropValue(object src, string propName)
        {
            return Convert.ToString(src.GetType().GetProperty(propName).GetValue(src, null));
        }
    }
}

Areas/Logging/Views/ManageLog/List.cshtml
@model DataRooms.UI.Areas.Logging.Models.ActivityLogModel
@using PagedList.Mvc;
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_BootstrapLayout.cshtml";
}

@*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@

<div class="content-header pb-0">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/dashboard">Home</a></li>
                    <li class="breadcrumb-item active">Activity Logs</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<form method="post" action="@Url.Action("List","ManageLog",new { area = "Logging"})" id="frmActivityLogList">
    <section class="content">
        <div class="container-fluid border-top">
            <h5 class="mt-2">Activity Logs</h5>
            <div class="row">
                <div class="table-responsive">
                    @Html.Partial("~/Areas/Logging/Views/Shared/_activityloglist.cshtml", Model.PagedActivityLogs)
                </div>
                <div class="ml-auto" align="center">
                    Page @(Model.PagedActivityLogs.PageCount < Model.PagedActivityLogs.PageNumber ? 0 : Model.PagedActivityLogs.PageNumber)
                    of @Model.PagedActivityLogs.PageCount
                    <input type="hidden" name="RecordsPerPage" value="@Model.RecordsPerPage" />
                    <input type="hidden" name="CurrentPage" id="hdnCurrentPage" value="@Model.CurrentPage" />
                    <input type="hidden" name="SortOrder" id="hdnSortOrder" value="@Model.SortOrder" />
                    <input type="hidden" name="SortColumn" id="hdnSortColumn" value="@Model.SortColumn" />
                    @Html.PagedListPager(Model.PagedActivityLogs, page => "#")
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</form>




<input type="button" data-toggle="modal" data-target="#datalogModel" id="btnShowDatalogModel" />
<div class="modal fade" id="datalogModel" tabindex="-1" role="dialog" aria-labelledby="logModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title theme" id="changeRoleModalLabel">Data Log</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="divLogModalContent"></div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/Jquery.ui.min.js"></script>
<script>

    //List Filter Functionality
    $("#txtSearch").change(function () {
        $("#frmActivityLogList").submit();
    });

    $(document).on("click", ".pagination li", function () {
        var currentPage = $(this).find('a').text();
        $("#hdnCurrentPage").val(currentPage);
        $("#frmActivityLogList").submit();
    });

    $(document).on("click", ".header", function () {
        var sortColumn = $(this).attr('data-column');
        var storedSortColumn = $("#hdnSortColumn").val();
        var sortOrder = $("#hdnSortOrder").val();
        debugger;
        if (sortColumn == storedSortColumn && sortOrder == "asc") {
            $("#hdnSortOrder").val("desc");
        }
        else {
            $("#hdnSortOrder").val("asc");
        }
        $("#hdnSortColumn").val(sortColumn);
        $("#frmActivityLogList").submit();
    });

    $(document).on("click", ".viewLog", function () {
        var id = $(this).attr("data-id");
        fnViewLog(id);
    });

    function fnViewLog(id) {
        $.ajax({
            type: "GET",
            url: "@Url.Action("GetDataLogsbyActivityLogId", "ManageLog",new { area = "Logging"})?activitylogid=" + id,
            data: {},
            async:true,
            dataType: "json",
            beforeSend: function () {
                formloader();
            },
            success: function (data) {
                $("#divLogModalContent").html('');
                $("#divLogModalContent").html(data.HTML);
                $("#btnShowDatalogModel").trigger("click");
                //$("#datalogModel").modal("show");
            },
            error: function (err) {

            },
            complete: function () {
                formloaderstop();
            }
        });
    };
</script>
